import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
// import Header from "@/components/Shared/Header/HeaderHome";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Start Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
