import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import Navber from "@/components/Navber";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Start Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <Navber /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
